### ISSUE TITLE
SceneMediator add/remove viewListener and  add/remove contextListener issue

### ISSUE THREAD

**Issue by gnunua** [RobotlegsJS/RobotlegsJS-Phaser#56]
## Expected Behavior

Make `addVewListener`, `removeVewListener`,` addContextListener` and `removeContextListener` fully functional on `SceneMediator` class.

## Current Behavior

`SceneMediator`should implement  methods 
`addVewListener`, `removeVewListener`,` addContextListener` and `removeContextListener`
I found those methods commented. 
<img width="749" alt="scenemediator" src="https://user-images.githubusercontent.com/5013933/45222777-75894800-b2c6-11e8-9b14-fc8fa2eef8b0.png">
Nothing is interrupt when uncommenting `addContextListener` and `removeContextListener`.
Those methods work fine because `eventDispatcher` implements `IEventDispatcher` interface.

The problem occurs with `addViewListener` and `removeViewListener` methods, because of `sceneComponent` is not implementing IEventDispacher interface. The first argument of `EventMap's `mapListner` method should implement `IEventDispatcher` interface.

## Possible Solution

- One of the possible solutions can be the following: 
Creating a class (RobotlegsScene) the will extend from `Phaser.Scene` and will implement `IEventDispatcher` interface. In that case  Robotlegs-phaser plugin all dependencies must be the form 
`RobotlegsScene` class instead of `Phaser.Scene`. 
Implementing `IEventDispatcher` could be very easy if we delegating appropriate methods to scenes event emitter. 
Here is some example that I am using in our code base. I have created `BaseScene` :
```javascript
export abstract class BaseScene extends Phaser.Scene implements IEventDispatcher {

 // implement
  public addEventListener(
    type: string | symbol,
    listener: () => void,
    context?: any,
  ): void {
    this.events.addListener(type, listener, context);
  }

// implement
  public removeEventListener(
    type: string | symbol,
    listener: () => void,
    context: any,
    once: boolean = false,
  ): void {
    this.events.removeListener(type, listener, context, once);
  }

  // implement
  public hasEventListener(type: string | symbol): boolean {
    return this.events.eventNames().indexOf(type) !== -1;
  }

  // implement
  public dispatchEvent(event?: IEvent): boolean {
    return this.events.emit(event.type || event.data);
  }

  // implement
  public willTrigger(type: string): boolean {
    return this.hasEventListener(type);
  }
  
  public init(): void { }

  public create(): void { }

}
```
- The other solution can be changing EventDispatcher in robotlegs-core to event-emitter. 
- Now, to use above mentioned methods you shold change your base scene class as I have metoned above. 

## Steps to Reproduce (for bugs)

1. Trigger context event from commands or form other mediators and your event listener method will not execute.
2. Now there is no ability to add view listener in mediators.

## Context

Mediators should be able to handle context events and view events.

## Your Environment

* @robotlegsjs/phaser version: v0.2.1
* Phaser version:  v3.12.0
* node version: v8.11.2
* npm version: v6.4.1
* Operating System and version (desktop or mobile): MacOS HighSierra version 10.13.6
* Link to your project: example project in this repo.

# Stack trace

There is no stack trace :)

## Addition
The same problem will occur after merging https://github.com/RobotlegsJS/RobotlegsJS-Phaser/pull/55 pull request with `Phaser.GameObject.Container`. We can implement the same   ##functionality for containers too.

**Comment by tiagoschenkel** [comment]
I'm already concerned about the **EventDispatcher** implementation present in the **@robotlegsjs/core** package. Initially, this implementation was added to the core to mimic the **EventDispatcher** implementation from the original **Flash/AS3** implementation.

Since the main concept behind the **core** package is to have a framework-agnostic approach, migrate to **eventemitter3** (or any other event emitter/dispatcher) will not solve the problem, since each framework ends up implementing their own approach.

For the **DisplayList** *like* frameworks (*PixiJS*, *CreateJS* and *OpenFL*), I'm already implementing one approach where the **RobotlegsJS** framework is not makin any assuption about how the display elements are triggering events. Mainly each framework specific plugin (*RobotlegsJS-Pixi*, *RobotlegsJS-CreateJS* or *RobotlegsJS-OpenFL*) will have to provide the concrete implementation of an **Observer**, who can then notify the framework about the events dispatched by each display element.

One better solution for this case could be the implementation of an **eventemitter3** package, who provides the implementation of the **eventCommandMap**, **eventDispatcher** and **localEventMap** extensions. This plugin can be named **RobotlegsJS-EventEmmiter3**, so it will be specific. This approach can benefit other plugins, since the **eventemitter3** is already used by the **PixiJS** framework (and maybe others).

I already have some ideas to remove any event specific implementation from the **@robotlegsjs/core** package because in the future...

**Comment by tiagoschenkel** [comment]
The package [@robotlegsjs/eventemitter3](https://www.npmjs.com/package/@robotlegsjs/eventemitter3) is extending now the interface `IEventMap` to support also events triggered by `eventemitter3` instances.

Now the `SceneMediator` and `ViewMediator` classes can inject the `IEventEmitterMap`, then the `addViewListener` and `removeViewListener` can be enabled without any problem.
